
server:

  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: API-GATEWAY

  datasource:
    url: jdbc:mysql://localhost:3306/hack2
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  cloud:
    gateway:
      routes:
        - id: USER-REGISTRATION-SERVICE
          uri: lb://USER-REGISTRATION-SERVICE
          predicates:
            - Path=/auth/**, /user/register/patient

        - id: DATACOLLECTION-SERVICE
          uri: lb://DATACOLLECTION-SERVICE
          predicates:
            - Path=/data/**

        - id: ALERTGENERATION-SERVICE
          uri: lb://ALERTGENERATION-SERVICE
          predicates:
            - Path=/generate/**

        - id: CONFIGURABILITY-SERVICE
          uri: lb://CONFIGURABILITY-SERVICE
          predicates:
            - Path=/config/**

        - id: DATAVISUALIZE-SERVICE
          uri: lb://DATAVISUALIZE-SERVICE
          predicates:
            - Path=/testreport/**