
server:
  port: 8099


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

spring:
  application:
    name: USER-REGISTRATION-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/hack2
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


