server:
  port: 0

spring:
  application:
    name: ALERT-NOTIFICATION-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

mail:
  id: rotatedsortedarray@gmail.com
  password: xoparjllqtizsyqz